package com.loan.application.service;

import com.loan.application.model.ApplicantDTO;
import com.loan.application.model.BusinessDTO;
import com.loan.application.model.LoanApplicationDTO;
import com.loan.application.model.LoanDetailsDTO;
import com.loan.application.entity.Applicant;
import com.loan.application.entity.Business;
import com.loan.application.entity.LoanApplication;
import org.springframework.stereotype.Service;

@Service
public class DtoMapperService {

    // --- Entity to DTO ---

    public LoanApplicationDTO toLoanApplicationDTO(LoanApplication entity) {
        if (entity == null) return null;
        return new LoanApplicationDTO(
                entity.getId(),
                toApplicantDTO(entity.getApplicant()),
                toBusinessDTO(entity.getBusiness()),
                toLoanDetailsDTO(entity), // Create LoanDetailsDTO from LoanApplication entity
                entity.getStatus(),
                entity.getSubmittedAt()
        );
    }

    public ApplicantDTO toApplicantDTO(Applicant entity) {
        if (entity == null) return null;
        return new ApplicantDTO(
                entity.getFirstName(),
                entity.getLastName(),
                entity.getEmail(),
                entity.getPhone(),
                entity.getSsn(),
                entity.getStreetAddress(),
                entity.getCity(),
                entity.getState(),
                entity.getZipCode()
        );
    }

    public BusinessDTO toBusinessDTO(Business entity) {
        if (entity == null) return null;
        return new BusinessDTO(
                entity.getName(),
                entity.getEin(),
                entity.getStreetAddress(),
                entity.getCity(),
                entity.getState(),
                entity.getZipCode(),
                entity.getType(),
                entity.getYearsInOperation(),
                entity.getAnnualRevenue()
        );
    }

     // Helper to create LoanDetailsDTO from LoanApplication entity
     private LoanDetailsDTO toLoanDetailsDTO(LoanApplication entity) {
        if (entity == null) return null;
        return new LoanDetailsDTO(
                entity.getLoanAmount(),
                entity.getLoanPurpose()
        );
     }


    // --- DTO to Entity ---

    public Applicant toApplicantEntity(ApplicantDTO dto) {
        if (dto == null) return null;
        Applicant entity = new Applicant();
        entity.setFirstName(dto.getFirstName());
        entity.setLastName(dto.getLastName());
        entity.setEmail(dto.getEmail());
        entity.setPhone(dto.getPhone());
        entity.setSsn(dto.getSsn());
        entity.setStreetAddress(dto.getStreetAddress());
        entity.setCity(dto.getCity());
        entity.setState(dto.getState());
        entity.setZipCode(dto.getZipCode());
        // ID and createdAt are generated by DB/JPA
        return entity;
    }

    public Business toBusinessEntity(BusinessDTO dto) {
        if (dto == null) return null;
        Business entity = new Business();
        entity.setName(dto.getName());
        entity.setEin(dto.getEin());
        entity.setStreetAddress(dto.getStreetAddress());
        entity.setCity(dto.getCity());
        entity.setState(dto.getState());
        entity.setZipCode(dto.getZipCode());
        entity.setType(dto.getType());
        entity.setYearsInOperation(dto.getYearsInOperation());
        entity.setAnnualRevenue(dto.getAnnualRevenue());
        // ID and createdAt are generated by DB/JPA
        return entity;
    }

    // LoanApplication entity is constructed directly in ApplicationService
}